version: "3.7"
services:
  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: milanomilano
    ports:
      - "5432:5432"
